name: Stop the cluster

on:
  workflow_dispatch:

jobs:
  
  container:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli:latest
    steps:
      - run: |
          az login --service-principal --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }} --output none         
          echo 'Fetching cluster status ...'
          CLUSTER_STATE=`az aks show --name k8s-cluster-01 --resource-group kubernetes-gettingstarted-rg --query 'powerState.code' -o json`
          echo $CLUSTER_STATE
          if [ "$CLUSTER_STATE" = "\"Stopped\"" ]; then
            echo "Starting the container."
          else
            echo "Stopping the container."
          fi
        name: Run in container


#az login --service-principal --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }} --output none
#echo 'Starting the cluster ...'
#az aks start --name k8s-cluster-01 --resource-group kubernetes-gettingstarted-rg
#echo 'Fetching cluster status ...'
#az aks show --name k8s-cluster-01 --resource-group kubernetes-gettingstarted-rg --query 'powerState.code' -o json
#echo 'Stoping the cluster ...'
#az aks stop --name k8s-cluster-01 --resource-group kubernetes-gettingstarted-rg



#docker run -it mcr.microsoft.com/azure-cli /bin/bash -c "az login --service-principal --username http://e0f2ee08-c641-4f9b-944d-9f59668daaa0 --password DT6.kZ~GPg-CeEv89a1BQQd4~j5E6rU6_A --tenant 4fa22c8d-4fb5-42ff-9e3d-1ff5770adce1 --output none; echo 'Fetching cluster status ...'; az aks show --name k8s-cluster-01 --resource-group kubernetes-gettingstarted-rg --query 'powerState.code' -o json"
