name: stop-cluster

on:
  schedule:
    - cron: '59 19 * * *'
  workflow_dispatch:
  
jobs:
  
  container:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli:latest
    steps:
      - run: |
          az login --service-principal --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }} --output none         
          echo 'Fetching cluster status ...'
          CLUSTER_STATE=`az aks show --name k8s-cluster-01 --resource-group kubernetes-gettingstarted-rg --query 'powerState.code' -o json`
          echo $CLUSTER_STATE
          if [ "$CLUSTER_STATE" = "\"Running\"" ]; then
            echo "Stopping the container ..."
            az aks stop --name k8s-cluster-01 --resource-group kubernetes-gettingstarted-rg
            echo " >> DONE"
          fi
        name: Run in container
